repos:
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.1.2 # Use the sha / tag you want to point at
    hooks:
      - id: biome-check
  - repo: local
    hooks:
      - id: ts-build
        name: npm run build
        entry: npm run build
        language: system
        pass_filenames: false
