repos:
  - repo: local
    hooks:
      - id: biome-check
        name: biome check
        entry: bunx biome check --write --staged --no-errors-on-unmatched --files-ignore-unknown=true
        language: system
        pass_filenames: false
      - id: ts-build
        name: bun run build
        entry: bun run build
        language: system
        pass_filenames: false
