ALTER TABLE sinks 
ADD COLUMN type VARCHAR(50),
ADD COLUMN is_display BOOLEAN NOT NULL DEFAULT 1,
ADD COLUMN height FLOAT NULL,
ADD COLUMN width FLOAT NULL,
ADD COLUMN amount INT NULL,
ADD COLUMN supplier VARCHAR(50) NULL;
