ALTER TABLE sales
ADD COLUMN cancelled_date DATETIME NULL,
ADD COLUMN installed_date DATETIME NULL,
ADD COLUMN square_feet DECIMAL(10,2) DEFAULT NULL,
ADD COLUMN paid_date DATETIME NULL,
ADD COLUMN notes TEXT DEFAULT NULL;