ALTER TABLE slab_inventory
ADD COLUMN edge VARCHAR(255),
ADD COLUMN room VARCHAR(255),
ADD COLUMN backsplash VARCHAR(255),
ADD COLUMN tear_out VARCHAR(255),
ADD COLUMN 10_year_sealer BOOLEAN,
ADD COLUMN waterfall VARCHAR(255),
ADD COLUMN corbels INT,
ADD COLUMN seam VARCHAR(255),
ADD COLUMN stove VARCHAR(255);

